---

title: "ANA 515 ASSIGNMENT 1"
output: html_document
Theme:
  bootswatch: Lumen
---


``` {r, echo = FALSE}
#install.packages("bslib")
#install.packages("tidyverse")
#install.packages("knitr")
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(knitr)
library(bslib)

```

```{r, echo = FALSE}
master_gun <- "https://raw.githubusercontent.com/fivethirtyeight/guns-data/master/full_data.csv"
gun_deaths <- read.csv(master_gun)

```

```{r, include = FALSE}
youth <- gun_deaths %>%
  filter(age <= 65)
```

```{r, include = FALSE}
summary(youth)
```


We have data about `r nrow(gun_deaths)` individuals killed by guns. Only `r nrow(gun_deaths) - nrow(youth)` are older than 65. The distribution of the remainder is shown below: 

```{R youth-dist, echo = FALSE}
youth %>%
ggplot(aes(age)) +
geom_freqpoly(binwidth=1)
```

```{r race-dist, echo = FALSE}
youth %>%
ggplot(aes(fct_infreq(race) %>% fct_rev())) +
geom_bar() + coord_flip() +
labs(x = "Victim race")
```